# apps/quality/views/__init__.py
from .scrap_views import ScrapDetailView
from .targets_views import QualityTargetView
from .qwall_views import (
    QWallReportView, QWallPartNumbersView, QWallTrendView, QWallParetoView,
    QWallFailByPointView, QWallBuSummaryView, QWallPartNumberSummaryView,
)
from .rejection_views import RejectionReportView, RejectionPhotoView, RejectionReportPDFView
from .failure_catalog_views import FailureCatalogView, CatalogStructureView
from .problem_views import (
    ProblemListCreateView,
    ProblemDetailView,
    ProblemSubmitView,
    ProblemApproveView,
    ProblemDepartmentApprovalView,
    ProblemRejectView,
    ProblemCloseView,
    ProblemOverrideRequestView,
    ProblemOverrideApproveView,
    SeverityLevelListView,
    DefectTypeListView,
    QualityUsersListView,
    ApprovalUsersListView,
    QualityManagersListView,
    ContainmentActionListCreateView,
    ContainmentActionDetailView,
    FiveWhyAnalysisListCreateView,
    FiveWhyAnalysisDetailView,
    RootCauseListCreateView,
    RootCauseDetailView,
    CorrectiveActionListCreateView,
    CorrectiveActionDetailView,
    VerificationActionListCreateView,
    VerificationActionDetailView,
    PreventionActionListCreateView,
    PreventionActionDetailView,
    ProblemAttachmentUploadView,
    ProblemAttachmentListView,
    ProblemAttachmentDeleteView,
    ProblemNoteListCreateView,
    ProblemNoteDetailView,
    ProblemCategoryListCreateView,
    ProblemCategoryDetailView,
    ProblemTypeListCreateView,
    ProblemTypeDetailView,
    DefectTypeDetailView,
)
from .approval_views import ProblemFinalApprovalView
from .approval_access_views import AssignedProblemFinalApprovalView, MyApprovalAssignmentsView
from .problem_control_settings_views import ProblemControlSettingsView
from .submit_approval_views import ProblemSubmitForFinalApprovalView
from .downtime_views import DowntimeLogsView, DowntimeTrendView, DowntimeSummaryView
from .downtime_workcenter_views import DowntimeWorkcentersView
from .downtime_assignment_views import DowntimeAssignmentsView

__all__ = [
    'FailureCatalogView',
    'CatalogStructureView',
    'ScrapDetailView',
    'QualityTargetView',
    'QWallReportView',
    'QWallPartNumbersView',
    'QWallTrendView',
    'QWallParetoView',
    'QWallFailByPointView',
    'QWallBuSummaryView',
    'QWallPartNumberSummaryView',
    'RejectionReportView',
    'RejectionPhotoView',
    'RejectionReportPDFView',
    'ProblemListCreateView',
    'ProblemDetailView',
    'ProblemSubmitView',
    'ProblemSubmitForFinalApprovalView',
    'ProblemApproveView',
    'ProblemDepartmentApprovalView',
    'ProblemFinalApprovalView',
    'AssignedProblemFinalApprovalView',
    'MyApprovalAssignmentsView',
    'ProblemControlSettingsView',
    'ProblemRejectView',
    'ProblemCloseView',
    'ProblemOverrideRequestView',
    'ProblemOverrideApproveView',
    'SeverityLevelListView',
    'DefectTypeListView',
    'QualityUsersListView',
    'ApprovalUsersListView',
    'QualityManagersListView',
    'ContainmentActionListCreateView',
    'ContainmentActionDetailView',
    'FiveWhyAnalysisListCreateView',
    'FiveWhyAnalysisDetailView',
    'RootCauseListCreateView',
    'RootCauseDetailView',
    'CorrectiveActionListCreateView',
    'CorrectiveActionDetailView',
    'VerificationActionListCreateView',
    'VerificationActionDetailView',
    'PreventionActionListCreateView',
    'PreventionActionDetailView',
    'ProblemAttachmentUploadView',
    'ProblemAttachmentListView',
    'ProblemAttachmentDeleteView',
    'ProblemNoteListCreateView',
    'ProblemNoteDetailView',
    'DowntimeLogsView',
    'DowntimeTrendView',
    'DowntimeSummaryView',
    'DowntimeWorkcentersView',
    'DowntimeAssignmentsView',
    'ProblemCategoryListCreateView',
    'ProblemCategoryDetailView',
    'ProblemTypeListCreateView',
    'ProblemTypeDetailView',
    'DefectTypeDetailView',
]
