# apps/quality/urls.py
from django.urls import path, include
from apps.permissions.drf import quality_view
from apps.quality.views import (
    FailureCatalogView,
    DowntimeLogsView,
    CatalogStructureView,
    ScrapDetailView,
    QualityTargetView,
    QWallReportView,
    QWallPartNumbersView,
    QWallTrendView,
    QWallParetoView,
    QWallFailByPointView,
    QWallBuSummaryView,
    QWallPartNumberSummaryView,
    RejectionReportView,
    RejectionPhotoView,
    RejectionReportPDFView,
    ProblemListCreateView,
    ProblemDetailView,
    ProblemSubmitForFinalApprovalView,
    ProblemApproveView,
    ProblemDepartmentApprovalView,
    AssignedProblemFinalApprovalView,
    MyApprovalAssignmentsView,
    ProblemControlSettingsView,
    ProblemRejectView,
    ProblemCloseView,
    ProblemOverrideRequestView,
    ProblemOverrideApproveView,
    SeverityLevelListView,
    DefectTypeListView,
    QualityUsersListView,
    ApprovalUsersListView,
    QualityManagersListView,
    ContainmentActionListCreateView,
    ContainmentActionDetailView,
    FiveWhyAnalysisListCreateView,
    FiveWhyAnalysisDetailView,
    RootCauseListCreateView,
    RootCauseDetailView,
    CorrectiveActionListCreateView,
    CorrectiveActionDetailView,
    VerificationActionListCreateView,
    VerificationActionDetailView,
    PreventionActionListCreateView,
    PreventionActionDetailView,
    ProblemAttachmentUploadView,
    ProblemAttachmentListView,
    ProblemAttachmentDeleteView,
    ProblemNoteListCreateView,
    ProblemNoteDetailView,
    DowntimeTrendView,
    FailureCatalogView,
    DowntimeLogsView,
    DowntimeTrendView,
    DowntimeSummaryView,
    DowntimeWorkcentersView,
    DowntimeAssignmentsView,
    CatalogStructureView,
    ProblemCategoryListCreateView,
    ProblemCategoryDetailView,
    ProblemTypeListCreateView,
    ProblemTypeDetailView,
    DefectTypeDetailView,
)

urlpatterns = [
    path("chatbot/", include("apps.quality.chatbot_urls")),
    path("scrap-detail/", quality_view(ScrapDetailView)),
    path("targets/", quality_view(QualityTargetView)),
    path("targets/<int:pk>/", quality_view(QualityTargetView)),
    path("qwall/", quality_view(QWallReportView)),
    path("qwall/trend/", quality_view(QWallTrendView)),
    path("qwall/pareto/", quality_view(QWallParetoView)),
    path("qwall/fail-by-point/", quality_view(QWallFailByPointView)),
    path("qwall/bu-summary/", quality_view(QWallBuSummaryView)),
    path("qwall/part-number-summary/", quality_view(QWallPartNumberSummaryView)),
    path("qwall/part-numbers/", quality_view(QWallPartNumbersView)),
    path("rejection-report/", quality_view(RejectionReportView)),
    path("rejection-photo/<int:inspection_id>/", quality_view(RejectionPhotoView)),
    path("rejection-report/pdf/", quality_view(RejectionReportPDFView)),

    # Problem Control CRUD / workflow
    path("problems/", quality_view(ProblemListCreateView), name="problem-list-create"),
    path("problems/my-approval-assignments/", MyApprovalAssignmentsView.as_view(), name="problem-my-approval-assignments"),
    path("problems/<int:pk>/", quality_view(ProblemDetailView), name="problem-detail"),
    path("problems/<int:pk>/submit/", quality_view(ProblemSubmitForFinalApprovalView, {"POST": "edit"}), name="problem-submit"),
    path("problems/<int:pk>/approve/", ProblemApproveView.as_view(), name="problem-approve"),
    path("problems/<int:pk>/department-approval/", ProblemDepartmentApprovalView.as_view(), name="problem-department-approval"),
    path("problems/<int:pk>/final-approvals/", AssignedProblemFinalApprovalView.as_view(), name="problem-final-approvals"),
    path("problems/<int:pk>/reject/", ProblemRejectView.as_view(), name="problem-reject"),
    path("problems/<int:pk>/close/", quality_view(ProblemCloseView, {"POST": "edit"}), name="problem-close"),
    path("problems/<int:pk>/override/request/", quality_view(ProblemOverrideRequestView, {"POST": "edit"}), name="problem-override-request"),
    path("problems/<int:pk>/override/approve/", quality_view(ProblemOverrideApproveView, {"POST": "edit"}), name="problem-override-approve"),

    # Problem Control settings / catalogs
    path("problem-control-settings/", quality_view(ProblemControlSettingsView), name="problem-control-settings"),
    path("severity-levels/", quality_view(SeverityLevelListView), name="severity-levels"),
    path("defect-types/", quality_view(DefectTypeListView), name="defect-types"),
    path("quality-users/", quality_view(QualityUsersListView), name="quality-users"),
    path("approval-users/", quality_view(ApprovalUsersListView), name="approval-users"),
    path("quality-managers/", quality_view(QualityManagersListView), name="quality-managers"),

    # Actions
    path("containment-actions/", quality_view(ContainmentActionListCreateView), name="containment-action-list"),
    path("containment-actions/<int:pk>/", quality_view(ContainmentActionDetailView), name="containment-action-detail"),
    path("five-why-analyses/", quality_view(FiveWhyAnalysisListCreateView), name="five-why-list"),
    path("five-why-analyses/<int:pk>/", quality_view(FiveWhyAnalysisDetailView), name="five-why-detail"),
    path("root-causes/", quality_view(RootCauseListCreateView), name="root-cause-list"),
    path("root-causes/<int:pk>/", quality_view(RootCauseDetailView), name="root-cause-detail"),
    path("corrective-actions/", quality_view(CorrectiveActionListCreateView), name="corrective-action-list"),
    path("corrective-actions/<int:pk>/", quality_view(CorrectiveActionDetailView), name="corrective-action-detail"),
    path("verification-actions/", quality_view(VerificationActionListCreateView), name="verification-action-list"),
    path("verification-actions/<int:pk>/", quality_view(VerificationActionDetailView), name="verification-action-detail"),
    path("prevention-actions/", quality_view(PreventionActionListCreateView), name="prevention-action-list"),
    path("prevention-actions/<int:pk>/", quality_view(PreventionActionDetailView), name="prevention-action-detail"),

    # Attachments / notes
    path("attachments/upload/", quality_view(ProblemAttachmentUploadView), name="attachment-upload"),
    path("attachments/", quality_view(ProblemAttachmentListView), name="attachment-list"),
    path("attachments/<int:pk>/", quality_view(ProblemAttachmentDeleteView), name="attachment-delete"),
    path("notes/", quality_view(ProblemNoteListCreateView), name="note-list-create"),
    path("notes/<int:pk>/", quality_view(ProblemNoteDetailView), name="note-detail"),

    # Quality catalogs / settings
    path("catalog/structure/", quality_view(CatalogStructureView), name="catalog-structure"),
    path("catalog/", quality_view(FailureCatalogView), name="failure-catalog"),
    path("qwall/settings/", include("apps.quality.qwall_settings_urls")),
    path("scan-rules/", include("apps.quality.scan_rules_urls")),
    path("incoming-inspection/", include("apps.quality.incoming_inspection_urls")),

    # Downtime / COGP
    path("downtime/logs/", quality_view(DowntimeLogsView), name="downtime-logs"),
    path("downtime/trend/", quality_view(DowntimeTrendView), name="downtime-trend"),
    path("cogp/", include("apps.quality.cogp_urls")),
    path("downtime/summary/", quality_view(DowntimeSummaryView), name="downtime-summary"),
    path("downtime/workcenters/", quality_view(DowntimeWorkcentersView), name="downtime-workcenters"),
    path("downtime/assignments/", DowntimeAssignmentsView.as_view(), name="downtime-assignments"),

    # Problem Control configurable catalogs
    path("problem-categories/", quality_view(ProblemCategoryListCreateView), name="problem-category-list-create"),
    path("problem-categories/<int:pk>/", quality_view(ProblemCategoryDetailView), name="problem-category-detail"),
    path("problem-types/", quality_view(ProblemTypeListCreateView), name="problem-type-list-create"),
    path("problem-types/<int:pk>/", quality_view(ProblemTypeDetailView), name="problem-type-detail"),
    path("defect-types/<int:pk>/", quality_view(DefectTypeDetailView), name="defect-type-detail"),
]
