# Generated by Django 5.1.4 on 2026-08-05 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
                'db_table': 'production_business_unit',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EarnedHoursRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('earned_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_hours_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Earned Hours Record',
                'db_table': 'production_earned_hours_record',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OEERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('availability_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oee_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OEE Record',
                'db_table': 'production_oee_record',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PlantEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('department', models.CharField(default='Assembly', max_length=100)),
                ('turno', models.CharField(choices=[('A', 'Turno A'), ('B', 'Turno B')], default='A', max_length=1)),
                ('barcode_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Barcode/Badge ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plant_employee', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema (opcional)')),
            ],
            options={
                'verbose_name': 'Plant Employee',
                'verbose_name_plural': 'Plant Employees',
                'db_table': 'production_plant_employee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(db_index=True, verbose_name='Fecha del incidente')),
                ('incident_type', models.CharField(choices=[('near_miss', 'Near Miss'), ('first_aid', 'First Aid'), ('recordable', 'Recordable'), ('lost_time', 'Lost Time'), ('covid_positive', 'COVID Positive'), ('property_damage', 'Property Damage'), ('environmental', 'Environmental')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('immediate_actions', models.TextField(blank=True)),
                ('root_cause', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Incident',
                'db_table': 'production_safety_incident',
                'ordering': ['-incident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(default='Tijuana', max_length=100, unique=True)),
                ('last_incident_date', models.DateField(blank=True, null=True)),
                ('baseline_date', models.DateField(blank=True, help_text='Ancla del conteo cuando aún no existe ningún incidente registrado.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Safety Settings',
                'verbose_name_plural': 'Safety Settings',
                'db_table': 'production_safety_settings',
            },
        ),
        migrations.CreateModel(
            name='SafetyCounterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Ajuste manual'), ('incident', 'Incidente reportado')], max_length=20)),
                ('previous_incident_date', models.DateField(blank=True, null=True)),
                ('new_incident_date', models.DateField(blank=True, null=True)),
                ('previous_days', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_counter_events', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_events', to='production.safetyincident')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_events', to='production.safetysettings')),
            ],
            options={
                'verbose_name': 'Safety Counter Event',
                'db_table': 'production_safety_counter_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Inicio de semana (lunes)')),
                ('general_target', models.IntegerField(default=0)),
                ('monday', models.IntegerField(blank=True, null=True)),
                ('tuesday', models.IntegerField(blank=True, null=True)),
                ('wednesday', models.IntegerField(blank=True, null=True)),
                ('thursday', models.IntegerField(blank=True, null=True)),
                ('friday', models.IntegerField(blank=True, null=True)),
                ('saturday', models.IntegerField(blank=True, null=True)),
                ('sunday', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_targets', to='production.businessunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_targets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly Target',
                'db_table': 'production_weekly_target',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyWIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='Inicio de semana (lunes)')),
                ('general_actual', models.IntegerField(default=0)),
                ('general_goal', models.IntegerField(default=0)),
                ('monday_actual', models.IntegerField(blank=True, null=True)),
                ('monday_goal', models.IntegerField(blank=True, null=True)),
                ('tuesday_actual', models.IntegerField(blank=True, null=True)),
                ('tuesday_goal', models.IntegerField(blank=True, null=True)),
                ('wednesday_actual', models.IntegerField(blank=True, null=True)),
                ('wednesday_goal', models.IntegerField(blank=True, null=True)),
                ('thursday_actual', models.IntegerField(blank=True, null=True)),
                ('thursday_goal', models.IntegerField(blank=True, null=True)),
                ('friday_actual', models.IntegerField(blank=True, null=True)),
                ('friday_goal', models.IntegerField(blank=True, null=True)),
                ('saturday_actual', models.IntegerField(blank=True, null=True)),
                ('saturday_goal', models.IntegerField(blank=True, null=True)),
                ('sunday_actual', models.IntegerField(blank=True, null=True)),
                ('sunday_goal', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_wips', to='production.businessunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_wips_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly WIP',
                'db_table': 'production_weekly_wip',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='CcsAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccs_employee_id', models.IntegerField(verbose_name='SQL Server employee ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(max_length=1)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('vacation', 'Vacation'), ('leave', 'Leave'), ('sick', 'Sick')], default='present', max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ccs_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_ccs_attendance',
                'ordering': ['-date'],
                'unique_together': {('ccs_employee_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('sick', 'Sick')], default='present', max_length=20)),
                ('shift', models.CharField(choices=[('full', 'Full'), ('partial', 'Partial'), ('overtime', 'Overtime'), ('none', '—')], default='full', max_length=20)),
                ('hours', models.DecimalField(decimal_places=1, default=12.0, max_digits=4)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_entered', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='production.plantemployee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'db_table': 'production_attendance_record',
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['incident_date', 'incident_type'], name='production__inciden_6a8054_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytarget',
            unique_together={('business_unit', 'week_start')},
        ),
        migrations.AlterUniqueTogether(
            name='weeklywip',
            unique_together={('business_unit', 'week_start')},
        ),
    ]
