# Generated by Django 5.1.4 on 2026-04-01 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial_production_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedHoursRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('earned_hours', models.DecimalField(decimal_places=1, default=0.0, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earned_hours_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Earned Hours Record',
                'db_table': 'production_earned_hours_record',
                'ordering': ['-date'],
            },
        ),
    ]
