# Generated by Django 5.1.4 on 2026-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('vacation', 'Vacation'), ('leave', 'Leave'), ('sick', 'Sick')], default='present', max_length=20),
        ),
    ]
