# Generated by Django 5.1.4 on 2026-04-06 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_add_earned_hours_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OEERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('availability_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('quality_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('oee_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oee_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OEE Record',
                'db_table': 'production_oee_record',
                'ordering': ['-date'],
            },
        ),
    ]
