# Generated by Django 5.1.4 on 2026-07-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_ccs_attendance_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ccsattendancerecord',
            name='unique_ccs_employee_date',
        ),
        migrations.AddField(
            model_name='plantemployee',
            name='barcode_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Barcode/Badge ID'),
        ),
        migrations.AlterField(
            model_name='ccsattendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='ccsattendancerecord',
            unique_together={('ccs_employee_id', 'date')},
        ),
    ]
