# Generated by Django 5.1.4 on 2026-08-04 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_ccsattendancerecord_unique_ccs_employee_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCounterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Ajuste manual'), ('incident', 'Incidente reportado')], max_length=20)),
                ('previous_incident_date', models.DateField(blank=True, null=True)),
                ('new_incident_date', models.DateField(blank=True, null=True)),
                ('previous_days', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Safety Counter Event',
                'db_table': 'production_safety_counter_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='safetysettings',
            options={'verbose_name': 'Safety Settings', 'verbose_name_plural': 'Safety Settings'},
        ),
        migrations.RemoveField(
            model_name='safetysettings',
            name='days_without_incident',
        ),
        migrations.AddField(
            model_name='safetysettings',
            name='baseline_date',
            field=models.DateField(blank=True, help_text='Ancla del conteo cuando aún no existe ningún incidente registrado.', null=True),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='incident_date',
            field=models.DateField(db_index=True, verbose_name='Fecha del incidente'),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='incident_type',
            field=models.CharField(choices=[('near_miss', 'Near Miss'), ('first_aid', 'First Aid'), ('recordable', 'Recordable'), ('lost_time', 'Lost Time'), ('covid_positive', 'COVID Positive'), ('property_damage', 'Property Damage'), ('environmental', 'Environmental')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='safetyincident',
            index=models.Index(fields=['incident_date', 'incident_type'], name='production__inciden_6a8054_idx'),
        ),
        migrations.AddField(
            model_name='safetycounterevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_counter_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safetycounterevent',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_events', to='production.safetyincident'),
        ),
        migrations.AddField(
            model_name='safetycounterevent',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_events', to='production.safetysettings'),
        ),
    ]
