# Generated by Django 5.1.4 on 2026-04-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bu', 'BU'), ('workcenter', 'Workcenter')], max_length=20)),
                ('bu', models.CharField(blank=True, max_length=20, null=True)),
                ('workcenter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('yield_min_pct', models.DecimalField(decimal_places=2, default=95.0, max_digits=5)),
                ('scrap_max_pct', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quality_target',
                'unique_together': {('level', 'bu', 'workcenter_name')},
            },
        ),
    ]
