# Generated by Django 5.1.4 on 2026-08-06 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group_key', models.CharField(max_length=100)),
                ('subgroup_key', models.CharField(blank=True, default='', max_length=50)),
                ('inspector_user_id', models.IntegerField(blank=True, null=True)),
                ('inspector_name', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'group_key', 'subgroup_key'],
                'indexes': [models.Index(fields=['date'], name='idx_downtime_grp_assign_date')],
                'constraints': [models.UniqueConstraint(fields=('date', 'group_key', 'subgroup_key'), name='uniq_downtime_group_assignment_per_day')],
            },
        ),
    ]
