# Generated by Django 5.1.4 on 2026-05-12 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSequence',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('current_value', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'problem_control_sequence',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_number', models.CharField(blank=True, db_index=True, help_text='Format: CA-WW-YY-NNNN (generated on approval)', max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sla_d3_hours', models.IntegerField(default=48, help_text='Initial Response SLA')),
                ('sla_d4_days', models.IntegerField(default=10, help_text='Containment SLA')),
                ('sla_d5_days', models.IntegerField(default=20, help_text='Five Why SLA')),
                ('sla_d6_days', models.IntegerField(default=20, help_text='Root Cause SLA')),
                ('sla_d7_days', models.IntegerField(default=30, help_text='Corrective Action SLA')),
                ('assigned_champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_championed', to=settings.AUTH_USER_MODEL)),
                ('assigned_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_quality', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problems_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_control_problem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLASettings',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('d3_hours', models.IntegerField(default=48, help_text='D3 Initial Response deadline (hours)')),
                ('d4_days', models.IntegerField(default=10, help_text='D4 Containment deadline (days)')),
                ('d5_days', models.IntegerField(default=20, help_text='D5 Five Why deadline (days)')),
                ('d6_days', models.IntegerField(default=20, help_text='D6 Root Cause deadline (days)')),
                ('d7_days', models.IntegerField(default=30, help_text='D7 Corrective Action deadline (days)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_control_sla_settings',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_code', models.CharField(choices=[('D1', 'D1 - Define Problem'), ('D2', 'D2 - Define Team'), ('D3', 'D3 - Initial Response'), ('D4', 'D4 - Containment'), ('D5', 'D5 - Five Why'), ('D6', 'D6 - Root Cause'), ('D7', 'D7 - Permanent Corrective Action'), ('D8', 'D8 - Verification Control')], max_length=3)),
                ('stage_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('due_date', models.DateTimeField(blank=True, help_text='Calculated from problem.created_at + SLA', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('override_requested', models.BooleanField(default=False)),
                ('override_approved', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('override_approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_assigned', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_completed', to=settings.AUTH_USER_MODEL)),
                ('override_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_approved', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='quality.problem')),
            ],
            options={
                'db_table': 'problem_control_stage',
                'ordering': ['stage_code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('override_requested', 'Override Requested'), ('override_approved', 'Override Approved'), ('override_rejected', 'Override Rejected'), ('stage_completed', 'Stage Completed')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(help_text='problem, stage, approval, override', max_length=50)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='quality.problem')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='quality.stage')),
            ],
            options={
                'db_table': 'problem_control_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['status', '-created_at'], name='problem_con_status_24cc27_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['created_by', '-created_at'], name='problem_con_created_c4b3ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='slasettings',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='sla_settings_singleton'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['problem', 'status'], name='problem_con_problem_8c955a_idx'),
        ),
        migrations.AddIndex(
            model_name='stage',
            index=models.Index(fields=['status', 'due_date'], name='problem_con_status_eb397f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('problem', 'stage_code')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['problem', '-created_at'], name='problem_con_problem_5c896b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='problem_con_user_id_7570b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='problem_con_action_595071_idx'),
        ),
    ]
