# Generated by Django 5.1.4 on 2026-08-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_downtimegroupassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpartmapping',
            name='classification_source',
            field=models.CharField(choices=[('CUSTOMER_NO', 'Customer_No directo'), ('NAME_FALLBACK', 'Nombre (fallback)'), ('CCS_OVERRIDE', 'CCS (fallback)'), ('UNMAPPED', 'Sin clasificar')], db_index=True, default='UNMAPPED', max_length=20),
        ),
    ]
