# Generated by Django 5.1.4 on 2026-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_alter_customerpartmapping_classification_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCategoryCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Problem Category',
                'verbose_name_plural': 'Problem Categories',
                'db_table': 'quality_problem_category',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTypeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Problem Type',
                'verbose_name_plural': 'Problem Types',
                'db_table': 'quality_problem_type',
                'ordering': ['label'],
            },
        ),
    ]
