# Generated by Django 5.1.4 on 2026-05-26 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_step_choices_and_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureModeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image_data', models.TextField(blank=True)),
                ('image_mime', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Failure Mode Entry',
                'verbose_name_plural': 'Failure Mode Entries',
                'db_table': 'quality_failure_mode_entry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bu', models.CharField(choices=[('cummins', 'Cummins'), ('volvo', 'Volvo'), ('tulc', 'TULC'), ('general', 'General')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspection Point',
                'verbose_name_plural': 'Inspection Points',
                'db_table': 'quality_inspection_point',
                'ordering': ['bu', 'order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='problemnote',
            new_name='quality_pro_problem_0cb2cf_idx',
            old_name='quality_pro_problem_note_idx',
        ),
        migrations.AlterField(
            model_name='fivewhyanalysis',
            name='corrective_action',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fivewhyanalysis',
            name='why4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fivewhyanalysis',
            name='why5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_number',
            field=models.CharField(blank=True, db_index=True, help_text='CA-WW-YY-XXXXX (generado al crear)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='problemnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rootcause',
            name='order',
            field=models.IntegerField(help_text='Número de fila (1, 2, 3, …)'),
        ),
        migrations.AddField(
            model_name='failuremodeentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_modes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='failuremodeentry',
            name='inspection_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='quality.inspectionpoint'),
        ),
        migrations.AddIndex(
            model_name='failuremodeentry',
            index=models.Index(fields=['inspection_point'], name='quality_fai_inspect_a91f72_idx'),
        ),
    ]
