# Generated by Django 5.1.4 on 2026-05-26 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_add_failure_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureModeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_point', models.CharField(max_length=300)),
                ('failure_mode', models.CharField(max_length=300)),
                ('image_data', models.TextField(blank=True)),
                ('image_mime', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_mode_images_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Failure Mode Image',
                'verbose_name_plural': 'Failure Mode Images',
                'db_table': 'quality_failure_mode_image',
            },
        ),
        migrations.DeleteModel(
            name='FailureModeEntry',
        ),
        migrations.DeleteModel(
            name='InspectionPoint',
        ),
        migrations.AddIndex(
            model_name='failuremodeimage',
            index=models.Index(fields=['inspection_point'], name='quality_fai_inspect_52373e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='failuremodeimage',
            unique_together={('inspection_point', 'failure_mode')},
        ),
    ]
