# Generated by Django 5.1.4 on 2026-07-16 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0013_fail_mode_translation_qwall_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingContainerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(db_index=True, max_length=100)),
                ('part_no', models.CharField(db_index=True, max_length=100)),
                ('part_key', models.BigIntegerField(null=True)),
                ('operation_no', models.IntegerField(db_index=True)),
                ('change_date', models.DateTimeField(db_index=True)),
                ('last_action', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('container_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('defect_type', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('change_by', models.CharField(blank=True, max_length=150, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incoming Container History',
                'db_table': 'quality_incoming_container_history',
            },
        ),
        migrations.CreateModel(
            name='IncomingContainerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_key', models.BigIntegerField(db_index=True, unique=True)),
                ('part_no', models.CharField(db_index=True, max_length=100)),
                ('part_operation_key', models.BigIntegerField(null=True)),
                ('operation_no', models.IntegerField(db_index=True)),
                ('location', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Incoming Container Snapshot',
                'db_table': 'quality_incoming_container_snapshot',
            },
        ),
        migrations.CreateModel(
            name='IncomingInspectionSLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_hours', models.PositiveIntegerField(default=48)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_value', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incoming Inspection SLA Config',
                'db_table': 'quality_incoming_inspection_sla_config',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomingInspectionSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('snapshot', 'Snapshot'), ('history', 'History')], max_length=20, unique=True)),
                ('last_synced_at', models.DateTimeField()),
                ('last_run_status', models.CharField(default='ok', max_length=20)),
                ('last_error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incoming Inspection Sync State',
                'db_table': 'quality_incoming_inspection_sync_state',
            },
        ),
        migrations.RenameIndex(
            model_name='failmodetranslation',
            new_name='quality_fai_fail_mo_7ffc6b_idx',
            old_name='quality_fai_fail_mo_2f6a1c_idx',
        ),
        migrations.AddIndex(
            model_name='incomingcontainerhistory',
            index=models.Index(fields=['change_date'], name='quality_inc_change__7a2791_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingcontainerhistory',
            index=models.Index(fields=['operation_no', 'change_date'], name='quality_inc_operati_a60d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='incomingcontainerhistory',
            index=models.Index(fields=['container_status'], name='quality_inc_contain_f38232_idx'),
        ),
        migrations.AddConstraint(
            model_name='incomingcontainerhistory',
            constraint=models.UniqueConstraint(fields=('serial_no', 'change_date', 'operation_no'), name='uq_incoming_history_dedup'),
        ),
        migrations.AddIndex(
            model_name='incomingcontainersnapshot',
            index=models.Index(fields=['operation_no', 'active'], name='quality_inc_operati_3abe1a_idx'),
        ),
        migrations.AddField(
            model_name='incominginspectionslaconfig',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
