# Generated by Django 5.1.4 on 2026-07-20 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0015_incoming_inspection_periodic_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('qwall', 'Q-Wall')], db_index=True, max_length=50)),
                ('question_key', models.SlugField(max_length=100, unique=True)),
                ('question_es', models.CharField(max_length=255)),
                ('question_en', models.CharField(max_length=255)),
                ('answer_template_es', models.TextField(blank=True)),
                ('answer_template_en', models.TextField(blank=True)),
                ('response_type', models.CharField(choices=[('text', 'Texto'), ('media_list', 'Lista con imágenes')], default='text', max_length=20)),
                ('service_method_ref', models.CharField(max_length=100)),
                ('required_filters', models.JSONField(blank=True, default=list)),
                ('role_slugs_allowed', models.JSONField(blank=True, default=list)),
                ('config_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot: Pregunta',
                'verbose_name_plural': 'Chatbot: Preguntas',
                'db_table': 'quality_chatbot_question_template',
                'ordering': ['module', 'display_order', 'question_key'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_helpful', models.BooleanField()),
                ('filters_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_feedback', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='quality.chatbotquestiontemplate')),
            ],
            options={
                'verbose_name': 'Chatbot: Feedback',
                'verbose_name_plural': 'Chatbot: Feedback',
                'db_table': 'quality_chatbot_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='qwall', max_length=50)),
                ('suggestion_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot: Sugerencia',
                'verbose_name_plural': 'Chatbot: Sugerencias',
                'db_table': 'quality_chatbot_suggestion',
                'ordering': ['-created_at'],
            },
        ),
    ]
