# Generated by Django 5.1.4 on 2026-07-27 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0016_chatbotquestiontemplate_chatbotfeedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingRejectionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(db_index=True, max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incoming Rejection Comment',
                'db_table': 'quality_incoming_rejection_comment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['serial_no', '-created_at'], name='quality_inc_serial__abf3ce_idx')],
            },
        ),
    ]
