# Generated by Django 5.1.4 on 2026-07-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0017_incomingrejectioncomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='COGPDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('business_unit', models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('SPEED', 'Speed')], db_index=True, max_length=20)),
                ('scrap_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extended_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cogp_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cogp_daily_summary',
                'indexes': [models.Index(fields=['report_date', 'business_unit'], name='cogp_daily__report__722b6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_date', 'business_unit'), name='uq_cogp_summary_dedup')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPartMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('part_name', models.CharField(blank=True, max_length=255)),
                ('part_status', models.CharField(blank=True, max_length=50)),
                ('customer_no', models.IntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('business_unit', models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('SPEED', 'Speed')], db_index=True, max_length=20)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cogp_customer_part_mapping',
                'indexes': [models.Index(fields=['business_unit'], name='cogp_custom_busines_3f2131_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('part_no', models.CharField(db_index=True, max_length=50)),
                ('workcenter', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('extended_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_model_key', models.IntegerField()),
                ('business_unit', models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('SPEED', 'Speed')], db_index=True, max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cogp_production_record',
                'indexes': [models.Index(fields=['report_date', 'business_unit'], name='cogp_produc_report__3873b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_date', 'part_no', 'workcenter'), name='uq_production_record_dedup')],
            },
        ),
        migrations.CreateModel(
            name='ScrapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('scrap_date', models.DateTimeField()),
                ('part_no', models.CharField(db_index=True, max_length=50)),
                ('part_type', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('scrap_reason', models.CharField(blank=True, max_length=255)),
                ('workcenter', models.CharField(blank=True, max_length=255)),
                ('workcenter_group', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('extended_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.TextField(blank=True)),
                ('business_unit', models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('SPEED', 'Speed')], db_index=True, max_length=20)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cogp_scrap_record',
                'indexes': [models.Index(fields=['report_date', 'business_unit'], name='cogp_scrap__report__e809fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('report_date', 'serial_no', 'scrap_date', 'part_no'), name='uq_scrap_record_dedup')],
            },
        ),
    ]
