# Generated by Django 5.1.4 on 2026-07-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0018_cogpdailysummary_customerpartmapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cogpdailysummary',
            name='business_unit',
            field=models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('TULC', 'TULC'), ('SPEED', 'Speed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customerpartmapping',
            name='business_unit',
            field=models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('TULC', 'TULC'), ('SPEED', 'Speed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='business_unit',
            field=models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('TULC', 'TULC'), ('SPEED', 'Speed')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scraprecord',
            name='business_unit',
            field=models.CharField(choices=[('VOLVO', 'Volvo'), ('JOHN_DEERE', 'John Deere'), ('CUMMINS', 'Cummins'), ('HARLEY_DAVIDSON', 'Harley-Davidson'), ('EATON', 'Eaton'), ('TULC', 'TULC'), ('SPEED', 'Speed')], db_index=True, max_length=20),
        ),
    ]
