# Generated by Django 5.1.4 on 2026-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0019_alter_cogpdailysummary_business_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpartmapping',
            name='classification_source',
            field=models.CharField(choices=[('CUSTOMER_NO', 'Customer_No directo'), ('NAME_FALLBACK', 'Nombre (fallback)'), ('UNMAPPED', 'Sin clasificar')], db_index=True, default='UNMAPPED', max_length=20),
        ),
    ]
