alter table "public"."identity_user" drop constraint "identity_user_employee_id_57931d20_uniq";

drop index if exists "public"."identity_user_employee_id_57931d20_uniq";

create table "public"."production_safety_counter_event" (
    "id" bigint generated by default as identity not null,
    "source" character varying(20) not null,
    "previous_incident_date" date,
    "new_incident_date" date,
    "previous_days" integer not null,
    "reason" text not null,
    "created_at" timestamp with time zone not null,
    "created_by_id" bigint,
    "incident_id" bigint,
    "settings_id" bigint not null
);


alter table "public"."production_safety_settings" drop column "days_without_incident";

alter table "public"."production_safety_settings" add column "baseline_date" date;

CREATE UNIQUE INDEX identity_user_employee_id_key ON public.identity_user USING btree (employee_id);

CREATE INDEX production__inciden_6a8054_idx ON public.production_safety_incident USING btree (incident_date, incident_type);

CREATE INDEX production_safety_counter_event_created_at_a6d7d972 ON public.production_safety_counter_event USING btree (created_at);

CREATE INDEX production_safety_counter_event_created_by_id_e9dde3ac ON public.production_safety_counter_event USING btree (created_by_id);

CREATE INDEX production_safety_counter_event_incident_id_45fa24e8 ON public.production_safety_counter_event USING btree (incident_id);

CREATE UNIQUE INDEX production_safety_counter_event_pkey ON public.production_safety_counter_event USING btree (id);

CREATE INDEX production_safety_counter_event_settings_id_b22830f7 ON public.production_safety_counter_event USING btree (settings_id);

CREATE INDEX production_safety_incident_incident_date_c97da28f ON public.production_safety_incident USING btree (incident_date);

CREATE INDEX production_safety_incident_incident_type_55c7d377 ON public.production_safety_incident USING btree (incident_type);

CREATE INDEX production_safety_incident_incident_type_55c7d377_like ON public.production_safety_incident USING btree (incident_type varchar_pattern_ops);

CREATE INDEX production_safety_incident_status_84ac0b6d ON public.production_safety_incident USING btree (status);

CREATE INDEX production_safety_incident_status_84ac0b6d_like ON public.production_safety_incident USING btree (status varchar_pattern_ops);

alter table "public"."production_safety_counter_event" add constraint "production_safety_counter_event_pkey" PRIMARY KEY using index "production_safety_counter_event_pkey";

alter table "public"."identity_user" add constraint "identity_user_employee_id_key" UNIQUE using index "identity_user_employee_id_key";

alter table "public"."production_safety_counter_event" add constraint "production_safety_co_created_by_id_e9dde3ac_fk_identity_" FOREIGN KEY (created_by_id) REFERENCES identity_user(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."production_safety_counter_event" validate constraint "production_safety_co_created_by_id_e9dde3ac_fk_identity_";

alter table "public"."production_safety_counter_event" add constraint "production_safety_co_incident_id_45fa24e8_fk_productio" FOREIGN KEY (incident_id) REFERENCES production_safety_incident(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."production_safety_counter_event" validate constraint "production_safety_co_incident_id_45fa24e8_fk_productio";

alter table "public"."production_safety_counter_event" add constraint "production_safety_co_settings_id_b22830f7_fk_productio" FOREIGN KEY (settings_id) REFERENCES production_safety_settings(id) DEFERRABLE INITIALLY DEFERRED not valid;

alter table "public"."production_safety_counter_event" validate constraint "production_safety_co_settings_id_b22830f7_fk_productio";


