# Generated by Django 5.1.4 on 2026-08-05 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('equipment_id', models.CharField(blank=True, default='', max_length=100)),
                ('equipment_desc', models.CharField(blank=True, default='', max_length=255)),
                ('equipment_group', models.CharField(blank=True, default='', max_length=255)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('failure_type', models.CharField(blank=True, default='', max_length=100)),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('close_notes', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_validation', 'Pending Validation'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_corrective_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_corrective_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ca_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_ca_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='maintenance.correctiveaction')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ca_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_ca_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceDashboardTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=50, unique=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparison', models.CharField(choices=[('gte', '≥ Target'), ('lte', '≤ Target')], max_length=4)),
                ('label_es', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('unit', models.CharField(default='hrs', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_targets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Dashboard Target',
                'db_table': 'maintenance_dashboard_target',
                'ordering': ['metric_key'],
            },
        ),
    ]
