# Generated by Django 5.1.4 on 2026-04-22 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('equipment_id', models.CharField(blank=True, default='', max_length=100)),
                ('equipment_desc', models.CharField(blank=True, default='', max_length=255)),
                ('equipment_group', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_corrective_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_corrective_action',
                'ordering': ['-created_at'],
            },
        ),
    ]
