# Generated by Django 5.1.4 on 2026-04-22 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctiveaction',
            old_name='notes',
            new_name='close_notes',
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_corrective_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='failure_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_validation', 'Pending Validation'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=25),
        ),
        migrations.CreateModel(
            name='CorrectiveActionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.correctiveaction')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ca_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_ca_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='maintenance.correctiveaction')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ca_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maintenance_ca_history',
                'ordering': ['changed_at'],
            },
        ),
    ]
