# Generated by Django 5.1.4 on 2026-07-13 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

SEED_TARGETS = [
    {"metric_key": "mttr",         "target_value": 2,  "comparison": "lte", "unit": "hrs", "label_es": "MTTR",             "label_en": "MTTR"},
    {"metric_key": "mtbf",         "target_value": 40, "comparison": "gte", "unit": "hrs", "label_es": "MTBF",             "label_en": "MTBF"},
    {"metric_key": "availability", "target_value": 90, "comparison": "gte", "unit": "%",   "label_es": "Disponibilidad",   "label_en": "Availability"},
    {"metric_key": "performance",  "target_value": 85, "comparison": "gte", "unit": "%",   "label_es": "Rendimiento",      "label_en": "Performance"},
    {"metric_key": "quality",      "target_value": 98, "comparison": "gte", "unit": "%",   "label_es": "Calidad",          "label_en": "Quality"},
    {"metric_key": "oee",          "target_value": 65, "comparison": "gte", "unit": "%",   "label_es": "OEE",              "label_en": "OEE"},
]


def seed_targets(apps, schema_editor):
    MaintenanceDashboardTarget = apps.get_model("maintenance", "MaintenanceDashboardTarget")
    for item in SEED_TARGETS:
        MaintenanceDashboardTarget.objects.update_or_create(
            metric_key=item["metric_key"], defaults=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_rename_notes_correctiveaction_close_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceDashboardTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=50, unique=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comparison', models.CharField(choices=[('gte', '≥ Target'), ('lte', '≤ Target')], max_length=4)),
                ('label_es', models.CharField(max_length=100)),
                ('label_en', models.CharField(max_length=100)),
                ('unit', models.CharField(default='hrs', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_targets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Dashboard Target',
                'db_table': 'maintenance_dashboard_target',
                'ordering': ['metric_key'],
            },
        ),
        migrations.RunPython(seed_targets, migrations.RunPython.noop),
    ]
