# Generated by Django 5.1.4 on 2026-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar')], max_length=10, verbose_name='Acción')),
                ('module', models.CharField(blank=True, max_length=50, verbose_name='Módulo')),
                ('resource', models.CharField(blank=True, max_length=100, verbose_name='Recurso')),
                ('resource_id', models.CharField(blank=True, max_length=50, verbose_name='ID Recurso')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha/Hora')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
