# Generated by Django 5.1.4 on 2026-03-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operador', 'Operador'), ('tecnico', 'Técnico'), ('lider', 'Líder de Línea'), ('supervisor', 'Supervisor'), ('ingeniero', 'Ingeniero'), ('admin', 'Administrador MES'), ('gerente', 'Gerente')], default='operador', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Empleado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10, verbose_name='Idioma preferido'),
        ),
    ]
