# Generated by Django 5.1.4 on 2026-03-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_user_avatar'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', through='permissions.UserRole', to='permissions.role', verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('operador', 'Operador'), ('tecnico', 'Técnico'), ('lider', 'Líder de Línea'), ('supervisor', 'Supervisor'), ('ingeniero', 'Ingeniero'), ('admin', 'Administrador MES'), ('gerente', 'Gerente')], default='operador', max_length=20, null=True, verbose_name='Rol (legacy)'),
        ),
    ]
