# Generated by Django 5.1.4 on 2026-03-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_user_roles_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
