# Generated by Django 5.1.4 on 2026-03-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_remove_legacy_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último acceso'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/Tijuana', max_length=60, verbose_name='Zona horaria'),
        ),
    ]
