# Generated by Django 5.1.4 on 2026-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_user_last_login_at_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Puesto'),
        ),
    ]
